# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work', '0002_auto_20170802_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpost',
            name='post_body',
        ),
        migrations.AddField(
            model_name='workpost',
            name='post_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
