# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work', '0003_auto_20171225_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=models.CharField(max_length=250))),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='post_author',
        ),
        migrations.DeleteModel(
            name='WorkPost',
        ),
    ]
