# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work', '0005_work_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
