# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(max_length=250, unique_for_date='post_publish'),
        ),
    ]
