# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 14:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170713_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=tinymce.models.HTMLField(),
        ),
    ]
