# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170716_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
