# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170714_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=models.TextField(),
        ),
    ]
