# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=250)),
                ('site_owner_name', models.CharField(max_length=250)),
                ('site_owner_email', models.CharField(max_length=250)),
                ('site_owner_twitter', models.CharField(max_length=250)),
                ('site_tagline', models.CharField(max_length=250)),
                ('site_footer', models.TextField()),
            ],
        ),
    ]
